# Generated by Django 4.2.1 on 2023-05-13 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharm_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ['name'], 'verbose_name': 'ЛС', 'verbose_name_plural': 'ЛС'},
        ),
        migrations.AlterModelOptions(
            name='druggroup',
            options={'ordering': ['title'], 'verbose_name': 'Группа ЛС', 'verbose_name_plural': 'Группы ЛС'},
        ),
        migrations.AlterModelOptions(
            name='ml_model',
            options={'ordering': ['time_update'], 'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название лекарственного средства'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='pg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharm_web.druggroup', verbose_name='Группа лекарственных средств'),
        ),
        migrations.CreateModel(
            name='DrugInteractionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interaction', models.TextField(verbose_name='Взаимодействие')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('DrugOne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='druginteractions_one', to='pharm_web.drug', verbose_name='ЛС №1')),
                ('DrugTwo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='druginteractions_two', to='pharm_web.drug', verbose_name='ЛС №2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Взаимодействие ЛС (Таблица)',
                'verbose_name_plural': 'Взаимодействие ЛС (Таблица)',
                'ordering': ['DrugOne'],
            },
        ),
    ]
