# Generated by Django 4.2.1 on 2023-09-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharm_web", "0002_alter_drug_options_alter_druggroup_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type_Drugs_MedScape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Type_en", models.CharField(max_length=255, verbose_name="Type Drug")),
                ("Type_ru", models.CharField(max_length=255, verbose_name="Тип ЛС")),
            ],
        ),
        migrations.CreateModel(
            name="Name_Drugs_MedScape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name_en", models.CharField(max_length=255, verbose_name="Name Drug")),
                (
                    "Name_ru",
                    models.CharField(max_length=255, verbose_name="Название ЛС"),
                ),
                (
                    "Group_Type",
                    models.ManyToManyField(to="pharm_web.type_drugs_medscape"),
                ),
            ],
        ),
    ]
