# Generated by Django 4.2.1 on 2023-09-14 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_web', '0002_alter_drug_options_alter_druggroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adverse_Effects_MedScape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adverse_effects_name_en', models.CharField(max_length=1000, verbose_name='Adverse Effects')),
                ('adverse_effects_name_ru', models.CharField(max_length=1000, verbose_name='Побочное действие')),
                ('adverse_effects_percent', models.CharField(max_length=1000, verbose_name='Процент')),
            ],
            options={
                'verbose_name': 'Побочные эффекты ЛС MedScape',
                'ordering': ['adverse_effects_percent'],
            },
        ),
        migrations.CreateModel(
            name='Pregnancy_and_lactation_MedScape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregnancy_common_en', models.CharField(max_length=10000, verbose_name='Pregnancy_common')),
                ('Pregnancy_specific_en', models.CharField(max_length=10000, verbose_name='Pregnancy_specific')),
                ('Lactation_common_en', models.CharField(max_length=10000, verbose_name='Lactation_common')),
                ('Lactation_specific_en', models.CharField(max_length=10000, verbose_name='Lactation_specific')),
                ('Pregnancy_common_ru', models.CharField(max_length=10000, verbose_name='Беременность')),
                ('Pregnancy_specific_ru', models.CharField(max_length=10000, verbose_name='Конкретные рекомендации для беременных')),
                ('Lactation_common_ru', models.CharField(max_length=10000, verbose_name='Грудное вскармливание')),
                ('Lactation_specific_ru', models.CharField(max_length=10000, verbose_name='Конкретные рекомендации для грудного вскармливания')),
            ],
            options={
                'verbose_name': 'Лактация ЛС MedScape',
            },
        ),
        migrations.CreateModel(
            name='Source_Drugs_MedScape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=1000, verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Источник информации о ЛС MedScape',
                'ordering': ['Source'],
            },
        ),
        migrations.CreateModel(
            name='Type_Drugs_MedScape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_en', models.CharField(max_length=255, verbose_name='Type Drug')),
                ('Type_ru', models.CharField(max_length=255, verbose_name='Тип ЛС')),
            ],
            options={
                'verbose_name': 'Тип ЛС MedScape',
                'ordering': ['Type_en'],
            },
        ),
        migrations.CreateModel(
            name='Warnings_MedScape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warnings_name_en', models.CharField(max_length=1000, verbose_name='Warnings')),
                ('warnings_name_ru', models.CharField(max_length=1000, verbose_name='Опасность')),
                ('warnings_type', models.CharField(max_length=1000, verbose_name='Тип опасности')),
            ],
            options={
                'verbose_name': 'Опасность применения  ЛС MedScape',
                'ordering': ['warnings_type'],
            },
        ),
        migrations.CreateModel(
            name='Name_Drugs_MedScape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_en', models.CharField(max_length=255, verbose_name='Name Drug')),
                ('Name_ru', models.CharField(max_length=255, verbose_name='Название ЛС')),
                ('Group_Type', models.ManyToManyField(to='pharm_web.type_drugs_medscape')),
            ],
            options={
                'verbose_name': 'МНН ЛС MedScape',
                'ordering': ['Name_en'],
            },
        ),
        migrations.CreateModel(
            name='Interaction_MedScape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_type_en', models.CharField(max_length=255, verbose_name='Classification Interaction')),
                ('classification_type_ru', models.CharField(max_length=255, verbose_name='Классификация взаимодействия')),
                ('description_en', models.CharField(max_length=10000, verbose_name='Description')),
                ('description_ru', models.CharField(max_length=10000, verbose_name='Описание')),
                ('interaction_with', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pharm_web.name_drugs_medscape')),
            ],
            options={
                'verbose_name': 'Взаимодействие ЛС MedScape',
                'ordering': ['classification_type_en'],
            },
        ),
        migrations.CreateModel(
            name='Drugs_information_MedScape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_File', models.CharField(max_length=255, verbose_name='Название файла с загруженной информацией')),
                ('Comment_en', models.CharField(max_length=255, verbose_name='Comment')),
                ('Comment_ru', models.CharField(max_length=255, verbose_name='Коментарий')),
                ('Adverse_Effects', models.ManyToManyField(to='pharm_web.adverse_effects_medscape')),
                ('Interaction', models.ManyToManyField(to='pharm_web.interaction_medscape')),
                ('Name_Drug', models.ManyToManyField(to='pharm_web.name_drugs_medscape')),
                ('Pregnancy_and_lactation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pharm_web.pregnancy_and_lactation_medscape')),
                ('Source_Drugs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pharm_web.source_drugs_medscape')),
                ('Warnings', models.ManyToManyField(to='pharm_web.warnings_medscape')),
            ],
            options={
                'verbose_name': 'Информация о ЛС MedScape',
                'ordering': ['Name_File'],
            },
        ),
    ]
