# Generated by Django 4.2.1 on 2023-10-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_web', '0003_adverse_effects_medscape_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source_drugs_medscape',
            name='Source',
            field=models.CharField(max_length=5000, verbose_name='Источник'),
        ),
    ]
